### ISSUE TITLE
Live sim redirecting to plain http

### ISSUE THREAD

**Issue by joeyparrish** [Dash-Industry-Forum/dash-live-source-simulator#97] opened 2020-05-19 19:22 UTC
When I request https://livesim.dashif.org/livesim/utc_head/testpic_2s/Manifest.mpd, I get redirected to the same URL with plain "http".  This results in a mixed content error and a failure in the Shaka Player demo: https://shaka-player-demo.appspot.com/demo/#asset=https://livesim.dashif.org/livesim/utc_head/testpic_2s/Manifest.mpd

Is something misconfigured on the live sim server?

This doesn't happen with https://livesim.dashif.org/dash/vod/testpic_2s/img_subs.mpd for some reason.

**Comment by wilaw** [comment] 2020-05-19 19:41
The SSL cert for this host was just rotated yesterday and it was mounted on a new EC2 instance. This behavior is likely correlated with that change.

@Torbjorn  - any idea why this is happening?

-Will

**Comment by TobbeEdgeware** [comment] 2020-05-24 20:47
Thanks for the bug report. The issue is fixed in version 2.0.1.

It was caused by a new version of mod_wsgi where the old way of distinguishing between https and http no longer worked.

**Closed** 2020-05-25 15:35 UTC
